# Generated by Django 3.1.4 on 2021-01-02 08:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpCamera',
            fields=[
                ('cam_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geohash', models.CharField(max_length=12)),
                ('dash_url', models.URLField(blank=True, max_length=65536, null=True)),
                ('hls_url', models.URLField(blank=True, max_length=65536, null=True)),
                ('src_url', models.CharField(max_length=65536)),
                ('online', models.BooleanField()),
                ('date_change', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['geohash'],
                'get_latest_by': ['online', 'date_charge'],
            },
        ),
        migrations.AddIndex(
            model_name='ipcamera',
            index=models.Index(fields=['geohash'], name='IpCam_geohash_idx'),
        ),
    ]
